name: React app deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
          python ./create_paths.py > ./src/media.js

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
